spring:
  cloud:
    gateway:
      routes:
        - id: order-route
          uri: lb://service-order
          predicates:
#            - Path=/api/order/**
            - name: Path
              args:
                patterns: /api/order/**
                matchTrailingSlash: true # 匹配末尾的/
          filters:
            - RewritePath=/api/order/?(?<segment>.*), /$\{segment} # (?<segment>.*)命名捕获组，segment是组名
            - OnceToken=X-Response-Token, jwt
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/?(?<segment>.*), /$\{segment}

        - id: bing-route
          uri: https://cn.bing.com/
          predicates:
            - name: Path
              args:
                patterns: /search
            - name: Query # 不同的名字代表了不同的类型，
            # AbstractRoutePredicateFactory的实现类是各种类型的断言工厂，可以根据对应类名来写-name
              args:
                param: q
                regexp: haha
            - Vip=user,miao # 实现自定义断言
      default-filters:
        - AddResponseHeader=X-Response-miao, 123